### ISSUE TITLE
why make this xrp-specific?

### ISSUE THREAD

**Issue by michielbdejong** [sharafian/ilp-plugin-xrp-asym#3]
I love the idea of providing a module that acts as many server-side paychan plugins, because that's what a connector will usually have. But do I understand correctly that this repo is xrp-specific? Could we "multiply" other [ilp-plu-pa-cha-fra](https://github.com/interledgerjs/ilp-plugin-payment-channel-framework)-based plugins in the same way?

**Comment by sharafian** [comment]
yeah, it's not actually based on payment-channel-framework anymore now that it's on the new LPI, but `ilp-plugin-btp` contains a generic BTP plugin that can be built off of for payment channel based plugins. We could restructure `ilp-plugin-mini-accounts` a little bit, and that would allow us to use that to generically create server-side plugins for many different ledgers

**Comment by michielbdejong** [comment]
OK, so if I understand correctly:
* ilp-plu-pa-cha-fra is deprecated
* ilp-plugin-btp is its successor
* to that, mini-accounts will add a WebSocket multiplexer on the server-side
* once you have plugin-btp + mini-accounts on the server-side, this repo only needs to add the xrp-specific things

But for now it also does part of plugin-btp's and mini-accounts's job. Right?

**Comment by sharafian** [comment]
yeah, that's correct

**Comment by sharafian** [comment]
now that the ilp-plugin-asym-server inherits ilp-plugin-mini-accounts, I think this is resolved. The base classes that can be extended are now `ilp-plugin-btp` and `ilp-plugin-mini-accounts`
