### ISSUE TITLE
repo description incorrect?

### ISSUE THREAD

**Issue by michielbdejong** [sharafian/ilp-plugin-xrp-asym#4]
Shouldn't the description of this repo read "Stateless XRP paychan client and Stateful multiplied XRP-paychan server" instead of just "Stateless XRP paychan client"?

**Comment by sharafian** [comment]
I believe this is more clear in the README now

**Comment by michielbdejong** [comment]
I meant the description at the top
<img width="878" alt="screen shot 2018-01-09 at 07 27 27" src="https://user-images.githubusercontent.com/408412/34707614-c67687da-f50e-11e7-8ec5-f81e52ab5101.png">
