### ISSUE TITLE
Add readme instructions

### ISSUE THREAD

**Issue by michielbdejong** [sharafian/ilp-plugin-xrp-asym#8]
https://github.com/sharafian/ilp-plugin-xrp-asym#ilp-plugin-xrp-asym only describes how to instantiate a client, and it's unclear which string is the secret (is it the 'secret' in `options.server` or the longer string in `options.secret`?)

I'll try to ping @sharafian or otherwise reverse-engineer the code to come up with a working client-server example like https://github.com/interledgerjs/ilp-plugin-payment-channel-framework#minimal-client-server-config-example

**Comment by sharafian** [comment]
added documentation about plugin options in the README
